# Generated by Django 4.0.1 on 2022-01-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
