# Generated by Django 4.0.1 on 2022-01-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='project_name',
            new_name='name',
        ),
    ]
