# Generated by Django 4.0.1 on 2022-01-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_task_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpermission',
            name='permission',
        ),
        migrations.AddField(
            model_name='projectpermission',
            name='permission',
            field=models.ManyToManyField(to='projects.Permission'),
        ),
    ]
